### ISSUE TITLE
Readme file and code in repo is not congruent

### ISSUE THREAD

**Issue by Nelsordo** [godfreynolan/DJITutorialsKotlin#1]
hi, how are you? i would like to ask you if in the tutorial of DJI in kotlin you changed the code in the github compared to the one shown in the readme file. At least in the register folder I followed the steps and it showed me an error when i ran it but then i ran the code in the repo and it worked fine.

**Comment by Nelsordo** [comment]
![image](https://user-images.githubusercontent.com/90015554/190499699-460bd154-4cc7-474d-9b0a-f8164a2983f4.png)

here is a log of the error that appears me

**Comment by godfreynolan** [comment]
Readme has been updated to match the code.
